//export all routes here 
import authRoutes from './auth.route';
import usersRoutes from './users.route';
import subscriptionsRoutes from './subscriptions.route';
import advisorsRoutes from './advisors.route';
import assignmentsRoutes from './assignments.route';
import goalsRoutes from './goals.route';
import reportsRoutes from './reports.route';
import meetingsRoutes from './meetings.route';
import notificationsRoutes from './notifications.route';
import analyticsRoutes from './analytics.route';
import auditLogsRoutes from './audit-logs.route';
import settingsRoutes from './settings.route';
import notesRoutes from './notes.route';
import express from 'express';
const router = express.Router();
router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/subscriptions', subscriptionsRoutes);
router.use('/advisors', advisorsRoutes);
router.use('/assignments', assignmentsRoutes);
router.use('/goals', goalsRoutes);
router.use('/reports', reportsRoutes);
router.use('/meetings', meetingsRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/audit-logs', auditLogsRoutes);
router.use('/settings', settingsRoutes);
router.use('/notes', notesRoutes);
export default router;